// <auto-generated />
using System;
using CMIS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMIS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515182229_AddBudgetStartEndYear")]
    partial class AddBudgetStartEndYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CMIS.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("AccountId")
                        .HasName("PRIMARY");

                    b.HasIndex("ChurchId");

                    b.HasIndex("DistrictId");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "fk_account_role");

                    b.HasIndex(new[] { "ProfileId" }, "profile_id")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("budget_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("BudgetId")
                        .HasName("PRIMARY");

                    b.HasIndex("ChurchId");

                    b.HasIndex("DistrictId");

                    b.ToTable("budget", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.BudgetAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("allocation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<decimal>("Allocated")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("allocated");

                    b.Property<int?>("BudgetId")
                        .HasColumnType("int")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Spent")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("spent");

                    b.HasKey("AllocationId")
                        .HasName("PRIMARY");

                    b.HasIndex("BudgetId");

                    b.ToTable("budget_allocation", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.BudgetProposal", b =>
                {
                    b.Property<int>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proposal_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProposalId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("level");

                    b.Property<int?>("MinistryId")
                        .HasColumnType("int")
                        .HasColumnName("ministry_id");

                    b.Property<string>("ProposalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("proposal_code");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<int>("SubmittedById")
                        .HasColumnType("int")
                        .HasColumnName("submitted_by_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("ProposalId")
                        .HasName("PRIMARY");

                    b.HasIndex("ChurchId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("MinistryId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("SubmittedById");

                    b.HasIndex(new[] { "ProposalCode" }, "proposal_code")
                        .IsUnique();

                    b.ToTable("budget_proposal", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.Church", b =>
                {
                    b.Property<int>("ChurchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChurchId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ChurchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("church_name");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("ChurchId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DistrictId" }, "fk_church_district");

                    b.ToTable("church", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("district_code");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("district_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("DistrictId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DistrictCode" }, "district_code")
                        .IsUnique();

                    b.ToTable("district", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.EquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("equipment_name");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_equipment", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedBudgetPerPerson")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("allocated_budget_per_person");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("duration");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<decimal>("ExpectedNumberOfParticipants")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("expected_number_of_participants");

                    b.Property<int>("ExpectedParticipants")
                        .HasColumnType("int")
                        .HasColumnName("expected_participants");

                    b.Property<string>("FundingType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("funding_type");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("OrganizingMinistry")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("organizing_ministry");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("target_audience");

                    b.Property<decimal>("TicketedPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("ticketed_price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.ExpenseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("expense_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("financial_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("item_name");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_expense", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.GuestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contact_number");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("GuestType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("guest_type");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_guest", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.LeadershipAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date")
                        .HasColumnName("assigned_date");

                    b.Property<int?>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("MinistryId")
                        .HasColumnType("int")
                        .HasColumnName("ministry_id");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("AssignmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ChurchId" }, "fk_leadership_church");

                    b.HasIndex(new[] { "DistrictId" }, "fk_leadership_district");

                    b.HasIndex(new[] { "MinistryId" }, "fk_leadership_ministry");

                    b.HasIndex(new[] { "ProfileId" }, "fk_leadership_profile");

                    b.HasIndex(new[] { "RoleId" }, "fk_leadership_role");

                    b.ToTable("leadership_assignment", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.Ministry", b =>
                {
                    b.Property<int>("MinistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ministry_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MinistryId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MinistryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ministry_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("MinistryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MinistryName" }, "ministry_name")
                        .IsUnique();

                    b.ToTable("ministry", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.PersonnelItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("personnel_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contact_number");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_personnel", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("ProfileStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("profile_status")
                        .HasDefaultValueSql("'Active'");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("enum('Male','Female')")
                        .HasColumnName("sex");

                    b.HasKey("ProfileId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ChurchId" }, "fk_profile_church");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.ProfileMinistry", b =>
                {
                    b.Property<int>("ProfileMinistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("profile_ministry_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfileMinistryId"));

                    b.Property<DateOnly?>("JoinedAt")
                        .HasColumnType("date")
                        .HasColumnName("joined_at");

                    b.Property<int>("MinistryId")
                        .HasColumnType("int")
                        .HasColumnName("ministry_id");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Inactive')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("ProfileMinistryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MinistryId" }, "fk_profile_ministry_ministry");

                    b.HasIndex(new[] { "ProfileId" }, "fk_profile_ministry_profile");

                    b.ToTable("profile_ministry", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.ProgramScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("ProgramTitle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("program_title");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_program_schedule", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleName" }, "role_name")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("BudgetAllocationId")
                        .HasColumnType("int")
                        .HasColumnName("budget_allocation_id");

                    b.Property<string>("BudgetLabel")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("budget_label");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("RecordedById")
                        .HasColumnType("int")
                        .HasColumnName("recorded_by_id");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transaction_code");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.HasKey("TransactionId")
                        .HasName("PRIMARY");

                    b.HasIndex("BudgetAllocationId");

                    b.HasIndex("RecordedById");

                    b.HasIndex(new[] { "TransactionCode" }, "transaction_code")
                        .IsUnique();

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.TransportationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transportation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_transportation", (string)null);
                });

            modelBuilder.Entity("CMIS.Models.Account", b =>
                {
                    b.HasOne("CMIS.Models.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_account_church");

                    b.HasOne("CMIS.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_account_district");

                    b.HasOne("CMIS.Models.Profile", "Profile")
                        .WithOne("Account")
                        .HasForeignKey("CMIS.Models.Account", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_profile");

                    b.HasOne("CMIS.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_account_role");

                    b.Navigation("Church");

                    b.Navigation("District");

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CMIS.Models.Budget", b =>
                {
                    b.HasOne("CMIS.Models.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_budget_church");

                    b.HasOne("CMIS.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_budget_district");

                    b.Navigation("Church");

                    b.Navigation("District");
                });

            modelBuilder.Entity("CMIS.Models.BudgetAllocation", b =>
                {
                    b.HasOne("CMIS.Models.Budget", "Budget")
                        .WithMany("Allocations")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_allocation_budget");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("CMIS.Models.BudgetProposal", b =>
                {
                    b.HasOne("CMIS.Models.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proposal_church");

                    b.HasOne("CMIS.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proposal_district");

                    b.HasOne("CMIS.Models.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proposal_ministry");

                    b.HasOne("CMIS.Models.Profile", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proposal_reviewed_by");

                    b.HasOne("CMIS.Models.Profile", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposal_submitted_by");

                    b.Navigation("Church");

                    b.Navigation("District");

                    b.Navigation("Ministry");

                    b.Navigation("ReviewedBy");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("CMIS.Models.Church", b =>
                {
                    b.HasOne("CMIS.Models.District", "District")
                        .WithMany("Churches")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("fk_church_district");

                    b.Navigation("District");
                });

            modelBuilder.Entity("CMIS.Models.EquipmentItem", b =>
                {
                    b.HasOne("CMIS.Models.EventModel", null)
                        .WithMany("Equipment")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMIS.Models.ExpenseItem", b =>
                {
                    b.HasOne("CMIS.Models.EventModel", null)
                        .WithMany("Expenses")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMIS.Models.GuestItem", b =>
                {
                    b.HasOne("CMIS.Models.EventModel", null)
                        .WithMany("Guests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMIS.Models.LeadershipAssignment", b =>
                {
                    b.HasOne("CMIS.Models.Church", "Church")
                        .WithMany("LeadershipAssignments")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leadership_church");

                    b.HasOne("CMIS.Models.District", "District")
                        .WithMany("LeadershipAssignments")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leadership_district");

                    b.HasOne("CMIS.Models.Ministry", "Ministry")
                        .WithMany("LeadershipAssignments")
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_leadership_ministry");

                    b.HasOne("CMIS.Models.Profile", "Profile")
                        .WithMany("LeadershipAssignments")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leadership_profile");

                    b.HasOne("CMIS.Models.Role", "Role")
                        .WithMany("LeadershipAssignments")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_leadership_role");

                    b.Navigation("Church");

                    b.Navigation("District");

                    b.Navigation("Ministry");

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CMIS.Models.PersonnelItem", b =>
                {
                    b.HasOne("CMIS.Models.EventModel", null)
                        .WithMany("Personnel")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMIS.Models.Profile", b =>
                {
                    b.HasOne("CMIS.Models.Church", "Church")
                        .WithMany("Profiles")
                        .HasForeignKey("ChurchId")
                        .IsRequired()
                        .HasConstraintName("fk_profile_church");

                    b.Navigation("Church");
                });

            modelBuilder.Entity("CMIS.Models.ProfileMinistry", b =>
                {
                    b.HasOne("CMIS.Models.Ministry", "Ministry")
                        .WithMany("ProfileMinistries")
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_ministry_ministry");

                    b.HasOne("CMIS.Models.Profile", "Profile")
                        .WithMany("ProfileMinistries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_ministry_profile");

                    b.Navigation("Ministry");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CMIS.Models.ProgramScheduleItem", b =>
                {
                    b.HasOne("CMIS.Models.EventModel", null)
                        .WithMany("ProgramSchedules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMIS.Models.Transaction", b =>
                {
                    b.HasOne("CMIS.Models.BudgetAllocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("BudgetAllocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transaction_allocation");

                    b.HasOne("CMIS.Models.Profile", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_recorded_by");

                    b.Navigation("Allocation");

                    b.Navigation("RecordedBy");
                });

            modelBuilder.Entity("CMIS.Models.TransportationItem", b =>
                {
                    b.HasOne("CMIS.Models.EventModel", null)
                        .WithMany("Transportation")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMIS.Models.Budget", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("CMIS.Models.Church", b =>
                {
                    b.Navigation("LeadershipAssignments");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("CMIS.Models.District", b =>
                {
                    b.Navigation("Churches");

                    b.Navigation("LeadershipAssignments");
                });

            modelBuilder.Entity("CMIS.Models.EventModel", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Expenses");

                    b.Navigation("Guests");

                    b.Navigation("Personnel");

                    b.Navigation("ProgramSchedules");

                    b.Navigation("Transportation");
                });

            modelBuilder.Entity("CMIS.Models.Ministry", b =>
                {
                    b.Navigation("LeadershipAssignments");

                    b.Navigation("ProfileMinistries");
                });

            modelBuilder.Entity("CMIS.Models.Profile", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("LeadershipAssignments");

                    b.Navigation("ProfileMinistries");
                });

            modelBuilder.Entity("CMIS.Models.Role", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("LeadershipAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
