using System;

namespace CMIS.Models;

/// <summary>
/// Maps to the record_summary table.
/// A persisted financial summary generated by authorized staff for a given period.
/// </summary>
public class RecordSummary
{
    public int SummaryId { get; set; }

    /// <summary>FK to Profile (the staff member who generated this summary)</summary>
    public int GeneratedBy { get; set; }

    public decimal TotalIncome { get; set; }

    public decimal TotalExpenses { get; set; }

    /// <summary>Computed as TotalIncome - TotalExpenses</summary>
    public decimal NetBalance { get; set; }

    /// <summary>e.g. "May 2026", "Q1 2026", "January 1–31, 2026"</summary>
    public string SummaryPeriod { get; set; } = null!;

    public DateTime GeneratedDate { get; set; }

    // Navigation
    public virtual Profile Generator { get; set; } = null!;
}
